name: pre-commit

on:
  push:
    branches: [master, main, test-*]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: 3.14
    - name: Run pre-commit
      uses: pre-commit/action@v3.0.1
